added poetry for simplifying building and running the package
berkerdemoglu/md-2-html pull request #9
Opened 2021-04-03 17:47 UTC by Seamooo

There are a changes in this PR
[poetry](https://python-poetry.org/) has been added for management of dependencies, packaging, and building
imports have been made to depend off the module `mdtohtml`
both the resources and assets have been moved inside the module file such that they may be accessed with relative imports
Small fixes have been added such that it's linux compatible.

Required Changes:
the pyproject.toml file will need to be filled out with author information, and a description of the project.
Additionally if there is a better name for the module this should be decided upon likely in this PR.

Nice to haves:
potentially the README should be populated with a developer section about poetry
ie that to run the application now it requires running `poetry install` then `poetry run python3 main.py`

Note: very little testing has been done, however the changes made have been tested

2021-04-04 19:01 UTC, berkerdemoglu reviewed
`poetry.lock`, `pyproject.toml` and tests package initializer are all fine.

2021-04-04 19:04 UTC, berkerdemoglu requested changes
However, the project's name is *md-2-html*, not *mdtohtml* so please change that. Another thing is, have you run the code? Does it produce the same result? What command did you use to run it?

2021-04-04 21:32 UTC, berkerdemoglu commented
Another comment, we should add actions to check if the code runs properly. create a new directory for the GUI as it looks as though it will need several files. put lexer in its own package

2021-04-05 03:35 UTC, Seamooo commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
@berkerdemoglu very minor but filling this out before deploying as a pypi package (if that's what you envision), is required.

2021-04-05 03:41 UTC, Seamooo commented
> However, the project's name is _md-2-html_, not _mdtohtml_ so please change that. Another thing is, have you run the code? Does it produce the same result? What command did you use to run it?

I mentioned how to run this in the original PR comment, but will expand in slightly more detail. Navigating to the repository (in root or subdirectory) run `poetry install`. This will install the dependencies of this package, and egg reference to the project in a cached venv. Navigating to `md_2_html` run `poetry run python main.py` to start the gui.

2021-04-05 03:43 UTC, Seamooo commented
> Another comment, we should add actions to check if the code runs properly. create a new directory for the GUI as it looks as though it will need several files. put lexer in its own package

Specifically for adding actions to check the code runs properly this should likely be done in a seperate PR as some additional specification is required for what's expected in terms of python-version / os compatibility

2021-04-05 12:49 UTC, berkerdemoglu commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
sure, i'll replace `Your Name <you@example.com>` with my name and my email after the PR. i will open an issue on deploying as a PyPI package.

2021-04-05 12:56 UTC, berkerdemoglu approved these changes

2021-04-05 13:55 UTC, Seamooo commented
ready to merge (I can't)

2021-04-05 15:39 UTC, berkerdemoglu commented
> ready to merge (I can't)

yes im just testing the code and making sure that everything works and i understand what's going on. will probably merge the PR tonight.

2021-04-06 10:55 UTC, merged